### ISSUE TITLE
findContours returned values changed with new version

### ISSUE THREAD

**Issue by marshf16** [noshluk2/ROS2-Self-Driving-Car-AI-using-OpenCV#3]
https://github.com/noshluk2/ROS2-Self-Driving-Car-AI-using-OpenCV/blob/03109f3ff8c02533a089bdace148f35326de7053/self_driving_car_pkg/self_driving_car_pkg/Detection/Lanes/Morph_op.py#L12

The 'findContours' function returns 2 values, 'contours' and 'hierarchy'. With this code, the hierarchy value is being assigned to 'cnts'.
Should the 'cnts' value be assigned to the contours value instead? Which can be done by changing the [1] in this line to [0], like so:
`cnts = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)[0]`

I read that the older version of OpenCV initially returned 3 values (image, contours, hierarchy) for this 'findContours' function, meaning this could be code written for an older version.

**Comment by HaiderAbasi** [comment]
**Exactly 'cnts' should be assigned the value of the contours.**

**->** project is running **OpenCV 3.4.15**

**(If you are running OpenCV 4 (FindContours) is slightly different. Just adjust it to that.)**

**a) findContour for OpenCV 3 (Repo):**
 > returns image, contours, hierarchy

**b) findContour for OpenCV 4 :**
 > returns contours, hierarchy

**Solution for OpenCV 4 users:**

**> Change**

`cnts = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)[1] `
 **to** 
`cnts = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)[0] `
