### ISSUE TITLE
For Windows

### ISSUE THREAD

**Issue by DoganK01** [noshluk2/ROS2-Self-Driving-Car-AI-using-OpenCV#8]
How can we setup ROS2 and Gazebo for Windows? I installed Docker, but I'm getting an error on it too. I can't download images.

**Comment by noshluk2** [comment]
Here is a video for windows and linux setup of docker

Link : https://youtu.be/qWuudNxFGOQ

In the last of this video, i am ran this course as an example on docker.

**Comment by DoganK01** [comment]
I know but when I try to download images, I'm getting error.

**Comment by DoganK01** [comment]
I can not install docker images: `docker pull osrf/ros:foxy-desktop` and etc.

**Comment by noshluk2** [comment]
kindly attach an image or paste log here so we can look at it .
